# kube-prometheus-stack

# Pas d'alertes pour l'instant
alertmanager:
  enabled: false

grafana:
  # Mot de passe administrateur lu depuis le Secret
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  resources:
    requests: { cpu: 50m, memory: 256Mi }
    limits: { memory: 512Mi }

prometheus:
  prometheusSpec:
    # 2 jours d'historique
    retention: 2d
    resources:
      requests: { cpu: 100m, memory: 400Mi }
      limits: { memory: 800Mi }
    # Pas de disque persistant

kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false