apiVersion: v1
kind: Secret
metadata:
  name: site-monitor-secrets
  namespace: site-monitor
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-moi"
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/..."