apiVersion: v1
kind: Pod
metadata:
  name: test-registry-w1
spec:
  nodeName: k8s-worker-1
  restartPolicy: Never
  containers:
    - name: test
      image: europe-west9-docker.pkg.dev/site-monitor-prk26/site-monitor/api:0.1.0
      command: ["python", "-c", "print('Image telechargee depuis Artifact Registry : OK')"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-registry-w2
spec:
  nodeName: k8s-worker-2
  restartPolicy: Never
  containers:
    - name: test
      image: europe-west9-docker.pkg.dev/site-monitor-prk26/site-monitor/api:0.1.0
      command: ["python", "-c", "print('Image telechargee depuis Artifact Registry : OK')"]